server.port: 8080
spring.application.name: fee-service-external

tUserService.endpoint: http://192.168.99.100:9000/user-service/thrift/user

---
spring:
  profiles: consul
tUserService.endpoint: http://gateway-server.service.consul:9000/user-service/thrift/user

---
spring:
  profiles: eureka
tUserService.endpoint: http://${APPLICATION_DOMAIN}:9000/user-service/thrift/user